<?php
$starNamesArray = array(
  "Acamar",
  "Achemar",
  "Achird",
  "Acrux",
  "Acubens",
  "Adhafera",
  "Adhil",
  "Ain",
  "Al Athfar",
  "Al Bali",
  "Al Dhanab",
  "Al Gieba",
  "Al Giedi",
  "Al Haud",
  "Al Nair",
  "Al Niyat",
  "Al Reschia",
  "Al Thalimain",
  "Aladfar",
  "Albireo",
  "Alchibah",
  "Alcor",
  "Alcyone",
  "Aldebaran",
  "Alderamin",
  "Alfirk",
  "Algenib",
  "Algol",
  "Algorab",
  "Alioth",
  "Alkaid",
  "Alkalurops",
  "Alkes",
  "Almach",
  "Almeisan",
  "Alnilam",
  "Alnitak",
  "Alphard",
  "Alpheratz",
  "Alsafi",
  "Alshain",
  "Altair",
  "Alterf",
  "Aludra",
  "Alula",
  "Alya",
  "Ancha",
  "Andromeda",
  "Angetenar",
  "Ankaa",
  "Antares",
  "Antlia",
  "Apus",
  "Aquarius",
  "Aquila",
  "Ara",
  "Arcturus",
  "Aries",
  "Arkab",
  "Arneb",
  "Arrakis",
  "Ascella",
  "Asellus",
  "Asmidiske",
  "Asterope",
  "Atik",
  "Atlas",
  "Atria",
  "Auriga",
  "Auva",
  "Avior",
  "Azelfafage",
  "Azha",
  "Baham",
  "Baten Kaitos",
  "Beid",
  "Bellatrix",
  "Betelgeuse",
  "Bootes",
  "Botein",
  "Caelum",
  "Camelopardalis",
  "Cancer",
  "Canes",
  "Canis Major",
  "Canis Minor",
  "Canopus",
  "Capella",
  "Caph",
  "Capricornus",
  "Carina",
  "Cassiopeia",
  "Castor",
  "Celaeno",
  "Centaurus",
  "Cepheus",
  "Cetus",
  "Chamaeleon",
  "Chara",
  "Cheleb",
  "Choo",
  "Circinus",
  "Columba",
  "Coma Berenices",
  "Cor Caroli",
  "Corona Australis",
  "Corona Borealis",
  "Corvus",
  "Coxa",
  "Crater",
  "Crux",
  "Cujam",
  "Cursa",
  "Cygnus",
  "Dabih",
  "Delphinus",
  "Deneb",
  "Deneb Algiedi",
  "Denebola",
  "Diphda",
  "Dorado",
  "Draco",
  "Dschubba",
  "Dubhe    Dubh",
  "Dziban",
  "Edasich",
  "El Nasl",
  "El Nath",
  "Electra",
  "Eltanin",
  "Enif",
  "Equuleus",
  "Er Rai",
  "Eridanus",
  "Fomalhaut",
  "Fornax",
  "Fornacius",
  "Fum al Samakah",
  "Furud",
  "Gacrux",
  "Gemini",
  "Gemma    Alphecca",
  "Giauzar",
  "Gienah",
  "Gomeisa",
  "Graffias",
  "Grumium",
  "Grus",
  "Hadar",
  "Hamal",
  "Heka",
  "Hercules",
  "Heze",
  "Homam",
  "Horologium",
  "Hydra",
  "Hydrus",
  "Hydri",
  "Indus",
  "Jabbah",
  "Jabhat al Akrab",
  "Kabdhilinan",
  "Kaffaljidhmah",
  "Kaus Australis",
  "Kaus Borealis",
  "Kaus Media",
  "Ke",
  "Keid",
  "Kerhah",
  "Kitalpha",
  "Kochab",
  "Kokab",
  "Kornephoros",
  "Kraz",
  "Kuma",
  "Lacerta",
  "Lacertae",
  "Leo",
  "Leo Minor",
  "Lepus",
  "Lesath",
  "Libra",
  "Lupus",
  "Lynx",
  "Lyra",
  "Maaz",
  "Maia",
  "Marfik",
  "Markab",
  "Massim",
  "Matar",
  "Mebsuta",
  "Megrez",
  "Mekbuda",
  "Men",
  "Menkalinan",
  "Menkar",
  "Menkent",
  "Menkib",
  "Mensa",
  "Mensae",
  "Merak",
  "Mirak",
  "Merope",
  "Mesarthim",
  "Miaplacidus",
  "Mimosa",
  "Minhar",
  "Minkar",
  "Mintaka",
  "Mira",
  "Mirach",
  "Mirak    Izar",
  "Mirfak",
  "Mirzam",
  "Mizar",
  "Monoceros",
  "Mothallah",
  "Muhlifain",
  "Muliphein",
  "Mulu-lizi",
  "Muphrid",
  "Musca",
  "Muscida",
  "Na",
  "Naos",
  "Nashira",
  "Nekkar",
  "Nihal",
  "Nodus",
  "Norma",
  "Nunki",
  "Nusakan",
  "Octans",
  "Ophiuchus",
  "Orion",
  "Pavo",
  "Pegasus",
  "Perseus",
  "Phact",
  "Phad",
  "Pherkab",
  "Phoenix",
  "Pictor",
  "Pisces",
  "Piscis",
  "Pleadies",
  "Pleione",
  "Polaris",
  "Pollux",
  "Porrima",
  "Praecipula",
  "Prijipati",
  "Primus",
  "Procyon",
  "Propus",
  "Puppis",
  "Pyxis",
  "Rana",
  "Ras Algethi",
  "Ras Alhague",
  "Ras Elased",
  "Rasalas",
  "Rastaban",
  "Regulus",
  "Reticulum",
  "Rigel",
  "Rotanev",
  "Ruchba",
  "Ruchbah",
  "Rukbah",
  "Rukbat",
  "Sabik",
  "Sadachbia",
  "Sadal Melik",
  "Sadal Suud",
  "Sadalbari",
  "Sadatoni",
  "Sadr",
  "Sagitta",
  "Sagittarius",
  "Sargas",
  "Sarin",
  "Scheat",
  "Schedar",
  "Schemali",
  "Scorpius",
  "Sculptor",
  "Scutulum",
  "Scutum",
  "Segin",
  "Serpens",
  "Sextans",
  "Sextantis",
  "Shaula",
  "Sheliak",
  "Sheratan",
  "Signus",
  "Sirius",
  "Situla",
  "Skat",
  "Spica",
  "Sualocin",
  "Suhail",
  "Sulafat",
  "Syrma",
  "Talitha Australis",
  "Talitha Borealis",
  "Tania Australis",
  "Tania Borealis",
  "Tarazed",
  "Tarf",
  "Taurus",
  "Taygeta",
  "Tegmine",
  "Tejat",
  "Telescopium",
  "Thabit",
  "The Garnet",
  "The Peacock",
  "Thuban",
  "Tian",
  "Triangulum",
  "Triangulum Australe",
  "Tsih",
  "Tucana",
  "Tyl    Kin Yu",
  "Ukdah",
  "Unuk Al Hay",
  "Ursa Major",
  "Ursa Minor",
  "Vega",
  "Vela",
  "Vindemiatrix",
  "Virgo",
  "Volans",
  "Vulpecula",
  "Wasat",
  "Wezen",
  "Wezn",
  "Yed Posterior",
  "Yed Prior",
  "Yildun",
  "Zaniah",
  "Zaurak",
  "Zavijava",
  "Zhou",
  "Zi",
  "Zi Ceng",
  "Zozma",
  "Zuben El Genubi",
  "Zuben Eschamali",
  "Zubenhakrabi"
);
?>
